name: pygbag_build
on: push

jobs:  
  build-pygbag:
    name: Test-pygbag
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
            python3 -m pip install pygbag
            python3 -m pygbag --build $GITHUB_WORKSPACE
    - name : "Upload to GitHub pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: build/web